# Generated by Django 2.1.7 on 2019-03-14 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='전공코드')),
                ('major_title', models.CharField(max_length=50, verbose_name='전공명')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentID', models.IntegerField(primary_key=True, serialize=False, verbose_name='학생코드')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='전화번호')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='주소')),
                ('hobby', models.CharField(blank=True, max_length=50, verbose_name='취미')),
                ('skill', models.CharField(blank=True, max_length=50, verbose_name='보유기술')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Major', verbose_name='전공')),
            ],
        ),
    ]
