# Generated by Django 2.1.7 on 2019-03-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='전공코드')),
                ('major_title', models.CharField(max_length=50, verbose_name='전공명')),
            ],
        ),
    ]
